### ISSUE TITLE
[BUG] App crash on downloading image by long pressing

### ISSUE THREAD

**Issue by Kita2345** [RocketScientists/Rocket#54] opened 2021-07-24 16:23 UTC
App crash 
Go to https://dopiaza.org/tools/datauri/examples/index.php long press image see error

**Comment by walkingice** [comment] 2021-08-02 15:37
Do you mean long pressing on the Cat image? Did you suffered an app crash?

I used a latest build on master branch, I didn't got app crash.  But the period of showing context menu seems too long to me.

**Comment by Kita2345** [comment] 2021-08-03 03:22
Yes
Long pressing on the Cat image causes an app crash

Pada Senin, 02 Agustus 2021, Julian Chu ***@***.***> menulis:

**Comment by walkingice** [comment] 2021-08-14 13:35
https://user-images.githubusercontent.com/54793/129447942-a15061c5-02f2-4a19-9665-3a4cbc30b1dd.mp4

I cannot reproduce this issue on my Pixel 2, maybe this is only reproducible on specific environment? Do you have any crash log?

**Comment by Kita2345** [comment] 2021-08-14 14:21
I cannot reproduce this issue again

Pada tanggal Sab, 14 Agu 2021 20.35, Julian Chu ***@***.***>
menulis:

**Comment by benjamin-cheng** [comment] 2021-12-11 05:09
Close this issue since it cannot be reproduced. Feel free to reopen it if you find other steps to reproduce it.

**Closed by benjamin-cheng** 2021-12-11 05:09 UTC
